apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: auth-api
          image: articlesregistry.azurecr.io/authentication-service:latest
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__AzureAppConfiguration
              valueFrom:
                secretKeyRef:
                  name: appconfig-secret
                  key: AzureAppConfiguration