services:
  authenticationservice:
    image: ${DOCKER_REGISTRY-}authenticationservice
    build:
      context: .
      dockerfile: AuthenticationService/Dockerfile

  articleservice:
    image: ${DOCKER_REGISTRY-}articleservice
    build:
      context: .
      dockerfile: ArticleService/Dockerfile

  notificationservice:
    image: ${DOCKER_REGISTRY-}notificationservice
    build:
      context: .
      dockerfile: NotificationService/Dockerfile

